### ISSUE TITLE
Method to return list of users for a specific project

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/pymesync#102]
For instance:

```
>>> ts.project_users(project="ff")
{'malcolm': ['member', 'manager'], 'jayne': ['member'], 'kaylee': ['member'], 'zoe': ['member'], 'hoban': ['member'], 'simon': ['spectator'], 'river': ['spectator'], 'derrial': ['spectator'], 'inara': ['spectator']}
```
Or the output could look like this:
```
>>> ts.project_users(project="ff")
{'managers': ['malcolm'], 'member': ['jayne', 'kaylee', 'zoe', 'hoban', 'simon', 'river', 'derrial'], 'spectator': ['inara']}
```

We could also provide the following functionality:
```
>>> ts.project_users(project="ff", type="name")
['malcolm', 'jayne', 'kaylee', 'zoe', ... , 'inara']
```
or
```
>>> ts.project_users(project="ff", type="manager")
['malcolm']
```
etc.

@MaraJade @LyonesGamer @Kennric thoughts on what the return should look like?

**Comment by MaraJade** [comment]
I'm a fan of the second one.

**Comment by matthewrsj** [comment]
@MaraJade thinking about it, pymesync's purpose is to give the user a pythonic representation of what the API returns, so I'm leaning towards the first option (since that is exactly what the API returns), with the functionality of the last option (so you don't have to check everyone's permissions if you just want the manager).

**Comment by matthewrsj** [comment]
per IRC conversation with @Kennric we are just providing the functionality of the first option, since the purpose of pymesync is to return what the API returns.

@MaraJade that means you will get a dict containing the user field of the project, as it is returned from the API. For now, any other logic will have to be done on the front-end.
