### ISSUE TITLE
Convert array of activity slugs to single activity slug

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/pymesync#147]
Inside the docs for get_activities() as well as inside get_activities() in mock_pymesync.py, activity slugs are mistakenly represented as lists of slugs instead of as a single slug. As this is not in compliance with the TimeSync API, this should be fixed.

**Comment by ElijahCaine** [comment]
@aaroncohen73 think this can be closed?

**Comment by aaroncohen73** [comment]
Closed via #148
