### ISSUE TITLE
Allow "start" and "end" query parameters to be submitted as strings

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/pymesync#167]
Currently, the "start" and "end" query parameters for `get_times` have to be sent as single item lists. It doesn't make much sense for these parameters to be submitted like that (And it's been the cause of a fair bit of annoyance for those such as myself who have been working on Pymesync frontends).

How the parameters must be submitted currently:

```
query_parameters = {
    ...
    "start": ["2016-07-01"],
    "end": ["2016-07-04"],
    ...
}
```

How the parameters should look:

```
query_parameters = {
    ...
    "start": "2016-07-01",
    "end": "2016-07-05",
    ...
}
```

**Comment by subnomo** [comment]
This was added in #171.
