### ISSUE TITLE
Allow initializing with an existing token

### ISSUE THREAD

**Issue by Kennric** [osuosl/pymesync#84]
In applications where state is not kept  between interactions with pymesync methods, it would be useful to be able to instantiate pymesync with a token already acquired from a previous instance's auth call. If pymseync is instantiated with token=some_token, it can skip the auth step and simply use that token in methods

How it might work in django/flask:
```python
login_view(request):
    ps = pymsynce(baseurl=url)
    ps.authenticate(request.username, request.password)
    my_token = ps.get_token()
    store_token_in_session(my_token)

time_entry_view(request):
    if request.type == POST
        my_token = session.my_token
        ps = pymsynce(baseurl=url, token=my_token)
        ps.create_time(request.all_my_parameters) # no auth step needed, we already have the token
```

**Comment by matthewrsj** [comment]
Simple, this only requires a conditional assignment in the constructor.
